# Generated by Django 6.0.3 on 2026-04-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveIntegerField()),
                ('a_tension', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('anemie', models.BooleanField(default=False)),
                ('maladie_sanguine', models.BooleanField(default=False)),
                ('dernier_don_medical_ok', models.BooleanField(default=True)),
                ('donneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneur')),
            ],
        ),
    ]
