# Generated by Django 6.0.3 on 2026-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
