# Generated by Django 6.0.3 on 2026-03-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hopital')),
            ],
        ),
    ]
