# Generated by Django 6.0.3 on 2026-04-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='accounts.donneur'),
        ),
    ]
