# Generated by Django 6.0.3 on 2026-03-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('quantite', models.PositiveIntegerField()),
                ('delai', models.DateField()),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Clôturé', 'Clôturé')], default='Ouvert', max_length=10)),
                ('description', models.TextField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hopital')),
            ],
        ),
    ]
