# Generated by Django 6.0.3 on 2026-03-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('groupes_cibles', models.CharField(help_text='Ex: A+, O-, B+', max_length=50)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hopital')),
            ],
        ),
    ]
