# Generated by Django 6.0.3 on 2026-04-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medicalprofile'),
        ('campagnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='campagnes.campagne')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='campagnes.creneau')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donneur')),
            ],
            options={
                'unique_together': {('donneur', 'creneau')},
            },
        ),
    ]
